<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
    <UseWpf>true</UseWpf>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\evopro.png" />
    <PackageReference Include="DynamicData" Version="9.4.33" />
    <Resource Include="Resources\evopro.png" />
    <PackageReference Include="Beckhoff.TwinCAT.Ads.Reactive" Version="7.0.317" />
    <PackageReference Include="DiffPlex" Version="1.9.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
    <PackageReference Include="ReactiveUI" Version="24.1.0" />
    <PackageReference Include="ReactiveUI.WPF" Version="24.1.0" />
    <ProjectReference Include="..\TwinCatAdsTool.Interfaces\TwinCatAdsTool.Interfaces.csproj" />
    <None Remove="Resources\twincat.png" />
    <Resource Include="Resources\twincat.png" />
  </ItemGroup>


</Project>
